#! /bin/bash

# world:
echo ' '
read -p 'Enter target world destination or d for default: ' input_choice

if [ “$input_choice” = “d” ]
then
 x-terminal-emulator -x roslaunch sweeping_robot world.launch 2>/dev/null &

else
 x-terminal-emulator -x roslaunch sweeping_robot world.launch world_file:=$input_choice 2>/dev/null &
fi

# teleop:
sleep 3 &&
x-terminal-emulator -x roslaunch sweeping_robot teleop.launch 2>/dev/null &
x-terminal-emulator -x roslaunch sweeping_robot rviz.launch 2>/dev/null &

# amcl:
sleep 3 &&
echo ' '
read -p 'Press any key to continue to adaptive MCL... ' -n1 -s
x-terminal-emulator -x roslaunch sweeping_robot amcl.launch 2>/dev/null &

# navigation:
sleep 3 &&
x-terminal-emulator -e rosrun sweeping_robot navigation_goal

echo ' '
echo 'Script Completed'
echo ' '
