controller_frequency: 10.0

TrajectoryPlannerROS:

  holonomic_robot: false
  acc_lim_x: 5.0
  acc_lim_y: 5.0
  acc_lim_theta: 6.28
  max_vel_x: 0.60
  min_vel_x: 0.10
  escape_vel: -0.10
  max_vel_theta: +0.785
  min_vel_theta: -0.785
  min_in_place_vel_theta: 0.0314

  controller_frequency: 10.0
  sim_time: 1.0
  vx_samples: 10
  vtheta_samples: 30

  meter_scoring: false
  pdist_scale: 0.4
  oscillation_reset_dist: 0.20

  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.2
