map_type: costmap

obstacle_range: 4.0
raytrace_range: 4.0

transform_tolerance: 0.2

# set this for circular sweeping robot:
robot_radius: 0.20
inflation_radius: 0.40

observation_sources: laser_scan_sensor

laser_scan_sensor: {
  sensor_frame: hokuyo, 
  data_type: LaserScan, 
  topic: /sweeping_robot/laserscanner/scan, 
  marking: true, 
  clearing: true
}
